server:
  port: 9908
spring:
  application:
    name: provider
swagger:
  base:
    package: com.zhy.frame.pool.disruptor.controller
  contact:
    email: author@zhy.com
    name: author
    url: ''
  description: frame demo 服务提供方
  title: authentication-resource
  url: ''
  version: 1.0
