rpc:
  server:
    authentication: http://localhost:8030
    provider: http://localhost:9901/
    authority: http://localhost:9010/
server:
  port: 8888
spring:
  application:
    name: gateway
  redis:
    database: 3
    port: 6379
    host: 10.20.128.234
  cloud:
    gateway:
      httpclient:
        ssl:
          #需要配置,gateway转发后台的https请求才不会报错
          useInsecureTrustManager: true
      routes:
        - id: dalaoyang
          uri: http://www.sina.com/
          predicates:
            - Path=/dalaoyang/**
        - id: juejin
          uri: https://www.baidu.com/
          predicates:
            - Path=/juejin/**
        - id: provider
          uri: ${rpc.server.provider}
          predicates:
            - Path=/frame/provider/**
          filters:
            - StripPrefix=0 # 表示在转发时去掉userapi
            # 熔断降级配置
            - name: Hystrix
              args:
                name: default
                fallbackUri: forward:/defaultfallback
            # redis限流 ， filter名称必须是RequestRateLimiter
            - name: RequestRateLimiter
              args:
                # 使用SpEL名称引用Bean，与上面新建的RateLimiterConfig类中的bean的name相同
                key-resolver: '#{@remoteAddrKeyResolver}'
                # 每秒最大访问次数
                redis-rate-limiter.replenishRate: 20
                # 令牌桶最大容量
                redis-rate-limiter.burstCapacity: 20

# hystrix 信号量隔离，3秒后自动超时
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000
  shareSecurityContext: true
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
frame:
  gateway:
    support: true
  white:
    support: false
  releaseServer:
    support: true
  allowable:
    support: true
  jwt:
    support: true
  shiro:
    support: true
swagger:
  base:
    package: com.zhy.frame.route.gateway.controller
  contact:
    email: author@zhy.com
    name: author
    url: ''
  description: 网关
  title: authentication-resource
  url: ''
  version: 1.0