spring:
  redis:
    host: 10.20.128.234
    port: 6379
    database: 3
  application:
    name: shiro-demo
server:
  port: 9010
# swagger配置
swagger:
  base:
    package: com.zhy
  contact:
    email: author@zhy.com
    name: author
    url: ''
  description: feign demo 客户端
  title: authentication-resource
  url: ''
  version: 1.0
rpc:
  demo:
    server: localhost:9060
feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
frame:
  jwt:
    support: true
  shiro:
    support: true