server:
  port: 9902
  httpPort: 8081
spring:
  application:
    name: customer
  redis:
    database: 3
    port: 6379
    host: 10.20.128.234
istio:
  namespace: lvmoney
  docker:
    image:
      tag: ${docker.tag}
      name: ${docker.image}
      pull: Always
    file:
      name: ${docker.jar}
      temp: /home
  yaml:
    cover: true
    replicas: 1
    version: v1
  master:
    ip: 192.168.1.181
rpc:
  server:
    gateway: http://localhost:8888
operating:
  environment: local
  internal: internal
swagger:
  base:
    package: com.zhy.demo.customer.controller
  contact:
    email: author@zhy.com
    name: author
    url: ''
  description: frame demo 服务调用方
  title: authentication-resource
  url: ''
  version: 1.0
custom:
  tomcat:
    https:
      schema: http