spring:
  data:
    cassandra:
      keyspace-name: domestic
      contact-points: 192.168.2.171
      port: 9042
      cluster-name: TestCluster
      consistency-level: one
      serial-consistency-level: one
server:
  port: 9908
swagger:
  base:
    package: com.zhy.frame.newsql.scylla
  contact:
    email: author@zhy.com
    name: author
    url: ''
  description: frame demo 服务提供方
  title: authentication-resource
  url: ''
  version: 1.0