server:
  port: 9909
  #你生成的证书名字

nacos:
  service:
    address: localhost
    port: 8848
spring:
  application:
    name: provider
  redis:
    database: 3
    port: 6379
    host: 10.20.128.234
redisson:
  address: redis://10.20.128.234:6379
  password:
swagger:
  base:
    package: com.zhy.demo.syn.controller
  contact:
    email: author@zhy.com
    name: author
    url: ''
  description: frame demo 服务提供方
  title: authentication-resource
  url: ''
  version: 1.0
